// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simpleResults.proto

#include "simpleResults.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace filebenchmark {
constexpr SimpleResults::SimpleResults(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : status_(0)
  , inf_time_ms_(0){}
struct SimpleResultsDefaultTypeInternal {
  constexpr SimpleResultsDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SimpleResultsDefaultTypeInternal() {}
  union {
    SimpleResults _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SimpleResultsDefaultTypeInternal _SimpleResults_default_instance_;
}  // namespace filebenchmark
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_simpleResults_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_simpleResults_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_simpleResults_2eproto = nullptr;

const uint32_t TableStruct_simpleResults_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::filebenchmark::SimpleResults, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::filebenchmark::SimpleResults, status_),
  PROTOBUF_FIELD_OFFSET(::filebenchmark::SimpleResults, inf_time_ms_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::filebenchmark::SimpleResults)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::filebenchmark::_SimpleResults_default_instance_),
};

const char descriptor_table_protodef_simpleResults_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023simpleResults.proto\022\rfilebenchmark\"4\n\r"
  "SimpleResults\022\016\n\006status\030\001 \001(\005\022\023\n\013inf_tim"
  "e_ms\030\002 \001(\005B5\n3com.securityandsafetything"
  "s.libraries.filebenchmarkb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_simpleResults_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_simpleResults_2eproto = {
  false, false, 153, descriptor_table_protodef_simpleResults_2eproto, "simpleResults.proto", 
  &descriptor_table_simpleResults_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_simpleResults_2eproto::offsets,
  file_level_metadata_simpleResults_2eproto, file_level_enum_descriptors_simpleResults_2eproto, file_level_service_descriptors_simpleResults_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_simpleResults_2eproto_getter() {
  return &descriptor_table_simpleResults_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_simpleResults_2eproto(&descriptor_table_simpleResults_2eproto);
namespace filebenchmark {

// ===================================================================

class SimpleResults::_Internal {
 public:
};

SimpleResults::SimpleResults(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:filebenchmark.SimpleResults)
}
SimpleResults::SimpleResults(const SimpleResults& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&status_, &from.status_,
    static_cast<size_t>(reinterpret_cast<char*>(&inf_time_ms_) -
    reinterpret_cast<char*>(&status_)) + sizeof(inf_time_ms_));
  // @@protoc_insertion_point(copy_constructor:filebenchmark.SimpleResults)
}

inline void SimpleResults::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&status_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&inf_time_ms_) -
    reinterpret_cast<char*>(&status_)) + sizeof(inf_time_ms_));
}

SimpleResults::~SimpleResults() {
  // @@protoc_insertion_point(destructor:filebenchmark.SimpleResults)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void SimpleResults::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SimpleResults::ArenaDtor(void* object) {
  SimpleResults* _this = reinterpret_cast< SimpleResults* >(object);
  (void)_this;
}
void SimpleResults::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SimpleResults::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SimpleResults::Clear() {
// @@protoc_insertion_point(message_clear_start:filebenchmark.SimpleResults)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&status_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&inf_time_ms_) -
      reinterpret_cast<char*>(&status_)) + sizeof(inf_time_ms_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SimpleResults::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          status_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 inf_time_ms = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          inf_time_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SimpleResults::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:filebenchmark.SimpleResults)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_status(), target);
  }

  // int32 inf_time_ms = 2;
  if (this->_internal_inf_time_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_inf_time_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:filebenchmark.SimpleResults)
  return target;
}

size_t SimpleResults::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:filebenchmark.SimpleResults)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 status = 1;
  if (this->_internal_status() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_status());
  }

  // int32 inf_time_ms = 2;
  if (this->_internal_inf_time_ms() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_inf_time_ms());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SimpleResults::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SimpleResults::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SimpleResults::GetClassData() const { return &_class_data_; }

void SimpleResults::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SimpleResults *>(to)->MergeFrom(
      static_cast<const SimpleResults &>(from));
}


void SimpleResults::MergeFrom(const SimpleResults& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:filebenchmark.SimpleResults)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_status() != 0) {
    _internal_set_status(from._internal_status());
  }
  if (from._internal_inf_time_ms() != 0) {
    _internal_set_inf_time_ms(from._internal_inf_time_ms());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SimpleResults::CopyFrom(const SimpleResults& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:filebenchmark.SimpleResults)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimpleResults::IsInitialized() const {
  return true;
}

void SimpleResults::InternalSwap(SimpleResults* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SimpleResults, inf_time_ms_)
      + sizeof(SimpleResults::inf_time_ms_)
      - PROTOBUF_FIELD_OFFSET(SimpleResults, status_)>(
          reinterpret_cast<char*>(&status_),
          reinterpret_cast<char*>(&other->status_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SimpleResults::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_simpleResults_2eproto_getter, &descriptor_table_simpleResults_2eproto_once,
      file_level_metadata_simpleResults_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace filebenchmark
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::filebenchmark::SimpleResults* Arena::CreateMaybeMessage< ::filebenchmark::SimpleResults >(Arena* arena) {
  return Arena::CreateMessageInternal< ::filebenchmark::SimpleResults >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
