// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simpleResults.proto

#include "simpleResults.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace filebenchmark {
class SimpleResultsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SimpleResults>
      _instance;
} _SimpleResults_default_instance_;
}  // namespace filebenchmark
namespace protobuf_simpleResults_2eproto {
static void InitDefaultsSimpleResults() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::filebenchmark::_SimpleResults_default_instance_;
    new (ptr) ::filebenchmark::SimpleResults();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::filebenchmark::SimpleResults::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SimpleResults =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSimpleResults}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SimpleResults.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::filebenchmark::SimpleResults, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::filebenchmark::SimpleResults, status_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::filebenchmark::SimpleResults, inf_time_ms_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::filebenchmark::SimpleResults)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::filebenchmark::_SimpleResults_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "simpleResults.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023simpleResults.proto\022\rfilebenchmark\"4\n\r"
      "SimpleResults\022\016\n\006status\030\001 \001(\005\022\023\n\013inf_tim"
      "e_ms\030\002 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 98);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "simpleResults.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_simpleResults_2eproto
namespace filebenchmark {

// ===================================================================

void SimpleResults::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SimpleResults::kStatusFieldNumber;
const int SimpleResults::kInfTimeMsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SimpleResults::SimpleResults()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_simpleResults_2eproto::scc_info_SimpleResults.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:filebenchmark.SimpleResults)
}
SimpleResults::SimpleResults(const SimpleResults& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&status_, &from.status_,
    static_cast<size_t>(reinterpret_cast<char*>(&inf_time_ms_) -
    reinterpret_cast<char*>(&status_)) + sizeof(inf_time_ms_));
  // @@protoc_insertion_point(copy_constructor:filebenchmark.SimpleResults)
}

void SimpleResults::SharedCtor() {
  ::memset(&status_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&inf_time_ms_) -
      reinterpret_cast<char*>(&status_)) + sizeof(inf_time_ms_));
}

SimpleResults::~SimpleResults() {
  // @@protoc_insertion_point(destructor:filebenchmark.SimpleResults)
  SharedDtor();
}

void SimpleResults::SharedDtor() {
}

void SimpleResults::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SimpleResults::descriptor() {
  ::protobuf_simpleResults_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_simpleResults_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SimpleResults& SimpleResults::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_simpleResults_2eproto::scc_info_SimpleResults.base);
  return *internal_default_instance();
}


void SimpleResults::Clear() {
// @@protoc_insertion_point(message_clear_start:filebenchmark.SimpleResults)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&status_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&inf_time_ms_) -
      reinterpret_cast<char*>(&status_)) + sizeof(inf_time_ms_));
  _internal_metadata_.Clear();
}

bool SimpleResults::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:filebenchmark.SimpleResults)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 status = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 inf_time_ms = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &inf_time_ms_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:filebenchmark.SimpleResults)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:filebenchmark.SimpleResults)
  return false;
#undef DO_
}

void SimpleResults::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:filebenchmark.SimpleResults)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->status(), output);
  }

  // int32 inf_time_ms = 2;
  if (this->inf_time_ms() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->inf_time_ms(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:filebenchmark.SimpleResults)
}

::google::protobuf::uint8* SimpleResults::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:filebenchmark.SimpleResults)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->status(), target);
  }

  // int32 inf_time_ms = 2;
  if (this->inf_time_ms() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->inf_time_ms(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:filebenchmark.SimpleResults)
  return target;
}

size_t SimpleResults::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:filebenchmark.SimpleResults)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->status());
  }

  // int32 inf_time_ms = 2;
  if (this->inf_time_ms() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->inf_time_ms());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SimpleResults::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:filebenchmark.SimpleResults)
  GOOGLE_DCHECK_NE(&from, this);
  const SimpleResults* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SimpleResults>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:filebenchmark.SimpleResults)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:filebenchmark.SimpleResults)
    MergeFrom(*source);
  }
}

void SimpleResults::MergeFrom(const SimpleResults& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:filebenchmark.SimpleResults)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.status() != 0) {
    set_status(from.status());
  }
  if (from.inf_time_ms() != 0) {
    set_inf_time_ms(from.inf_time_ms());
  }
}

void SimpleResults::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:filebenchmark.SimpleResults)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SimpleResults::CopyFrom(const SimpleResults& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:filebenchmark.SimpleResults)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimpleResults::IsInitialized() const {
  return true;
}

void SimpleResults::Swap(SimpleResults* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SimpleResults::InternalSwap(SimpleResults* other) {
  using std::swap;
  swap(status_, other->status_);
  swap(inf_time_ms_, other->inf_time_ms_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SimpleResults::GetMetadata() const {
  protobuf_simpleResults_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_simpleResults_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace filebenchmark
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::filebenchmark::SimpleResults* Arena::CreateMaybeMessage< ::filebenchmark::SimpleResults >(Arena* arena) {
  return Arena::CreateInternal< ::filebenchmark::SimpleResults >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
